import "react-toastify/dist/ReactToastify.css";
import getCurrentUser from "./actions/getCurrentUser";
import Menu from "./components/Menu/Menu";
import "./globals.css";
import { NextAuthProvider } from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en" data-theme="mytheme">
      <body>
        <NextAuthProvider>
          <Menu currentUser={currentUser} />
          <div className="flex flex-col items-start justify-start min-h-screen px-4 pt-20">
            {children}
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
